{% set name = "pyxsim" %}
{% set version = "4.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyxsim-{{ version }}.tar.gz
  sha256: c51c911655ae8bd21ad6af36f6e3670ee2f82fe1a429dcf24b8033bedff09713

build:
  skip: true  # [py<311]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python >=3.11
    - numpy
    - pip
    - cython >=0.29.21
    - setuptools >=45
    - setuptools_scm >=6.2
    - toml
    - wheel >=0.36.2
  run:
    - python >=3.11
    - astropy >=4.0
    - yt >=4.1.3
    - h5py >=3.0
    - scipy
    - tqdm
    - soxs >=4.3.0

test:
  imports:
    - pyxsim
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jzuhone/pyxsim
  summary: Synthetic X-ray Emission from Astrophysical Simulations
  license: BSD-3-Clause
  license_file: COPYING.txt

extra:
  recipe-maintainers:
    - jzuhone
